import Head from "next/head";
import styles from "@/styles/Home.module.css";

//importing components from components folder on root directory
import Navbar from "@/components/Navbar";
import Mlb from "@/components/Mlb";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cubs Play Today</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="/img/cubs.png" />
      </Head>
      <main className={styles.container}>
        <Navbar />
        <Mlb />
        <Footer />
      </main>
    </>
  );
}
